apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-aggregator-netstats
  namespace: vaas-prod
spec:
  chart:
    spec:
      chart: eth-cli
      interval: 5m
      version: '0.4.1'
      sourceRef:
        kind: HelmRepository
        name: kiln
        namespace: flux-system
  interval: 5m
  maxHistory: 2
