apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-aggregator-el
  namespace: vaas-prod
spec:
  chart:
    spec:
      chart: podinfo
      version: '0.4.1'
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: kiln
        namespace: flux-system
  interval: 5m
  maxHistory: 2
