apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-turbo-api
  namespace: vaas-prod
spec:
  chart:
    spec:
      chart: eth-cli
      interval: 5m
      version: '0.4.2'
      sourceRef:
        kind: HelmRepository
        name: kiln
        namespace: flux-system
  interval: 5m
  maxHistory: 2
  valuesFrom:
  - kind: ConfigMap
    name: vaas-version
  - kind: ConfigMap
    name: eth-base-config
    targetPath: eth.config
    optional: false
  values:
    resources:
      requests:
        cpu: 1
        memory: 1Gi
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 7
      targetCPUUtilizationPercentage: 65
    serviceAccount:
      create: true
      name: eth-turbo-api
    eth:
      bin: './entrypoint.sh'
      command: api
    env:
      ETH_API_POSTGRESQL_NETSTATS_DSN: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):$(POSTGRES_PORT)/eth_netstats?sslmode=verify-full"
      ETH_API_POSTGRESQL_EL_DSN: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):$(POSTGRES_PORT)/eth_el?sslmode=verify-full"
      ETH_API_POSTGRESQL_CL_DSN: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):$(POSTGRES_PORT)/eth_turbo_cl?sslmode=verify-full"
      ETH_API_POSTGRESQL_STAKES_DSN: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):$(POSTGRES_PORT)/eth_stakes?sslmode=verify-full"
      ETH_API_POSTGRESQL_DW_DSN: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):$(POSTGRES_PORT)/eth_deposits2?sslmode=verify-full"
      ETH_API_POSTGRESQL_EXIT_MESSAGES_DSN: "postgresql://$(POSTGRES_EXIT_MESSAGE_USERNAME):$(POSTGRES_EXIT_MESSAGE_PASSWORD)@$(POSTGRES_EXIT_MESSAGE_ENDPOINT):$(POSTGRES_EXIT_MESSAGE_PORT)/eth_exit_messages?sslmode=verify-full"
    envFrom:
      POSTGRES_ENDPOINT:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-reader-endpoint
      POSTGRES_PORT:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-port
      POSTGRES_USERNAME:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-username
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-password
      POSTGRES_EXIT_MESSAGE_ENDPOINT:
        valueFrom:
          secretKeyRef:
            name: eth-exit-messages-postgresql
            key: postgresql-reader-endpoint
      POSTGRES_EXIT_MESSAGE_PORT:
        valueFrom:
          secretKeyRef:
            name: eth-exit-messages-postgresql
            key: postgresql-port
      POSTGRES_EXIT_MESSAGE_USERNAME:
        valueFrom:
          secretKeyRef:
            name: eth-exit-messages-postgresql
            key: postgresql-username
      POSTGRES_EXIT_MESSAGE_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: eth-exit-messages-postgresql
            key: postgresql-password
    extraVolumes:
    - name: aws-rds-ca
      configMap:
        name: aws-rds-ca
        defaultMode: 0444
    extraVolumeMounts:
    - name: aws-rds-ca
      mountPath: /home/appuser/.postgresql
    nodeSelector:
      role: vaas
      network: private
    pdb:
      minAvailable: 0
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: eth-turbo-api
