---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-keygen
  namespace: vaas-prod
spec:
  chart:
    spec:
      chart: eth-cli
      version: '0.4.1'
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: kiln
        namespace: flux-system
  interval: 5m
  maxHistory: 2
  valuesFrom:
    - kind: ConfigMap
      name: eth-base-config
      targetPath: eth.config
      optional: false
    - kind: ConfigMap
      name: vaas-version
  values:
    replicaCount: 10
    serviceAccount:
      create: true
      name: 'eth-keygen'
    eth:
      bin: './entrypoint.sh'
      command: 'keygen'
    vault:
      enabled: true
      address: 'https://vault.kiln.fi'
      role: 'vaas-eth-keygen'
      certificate:
        duration: 36h
        renewBefore: 30h
        issuerRef:
          kind: ClusterIssuer
          name: vault-clusterissuer
    env:
      ETH_KEYGEN_POSTGRESQL_DSN: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):$(POSTGRES_PORT)/eth_stakes?sslmode=verify-full"
    enabledNetworkPolicy: true
    eksCIDR: "10.40.0.0/16"
    allowedEgressCIDRs:
      - "34.255.45.136/32" # NLB eu-west-1
      - "108.128.24.4/32" # NLB eu-west-1
      - "52.210.62.123/32" # NLB eu-west-1
      - "13.37.218.166/32" # NLB eu-west-3
      - "35.180.49.184/32" # NLB eu-west-3
      - "13.38.148.198/32" # NLB eu-west-3
      - "10.60.0.0/19" # RDS private subnet
      - "10.60.32.0/19" # RDS private subnet
    envFrom:
      POSTGRES_ENDPOINT:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-endpoint
      POSTGRES_PORT:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-port
      POSTGRES_USERNAME:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-username
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-password
    agentRefresh:
      enabled: true
    nodeSelector:
      node.kubernetes.io/instance-type: t3a.xlarge
      network: private
      role: dedicated
    extraVolumes:
    - name: aws-rds-ca
      configMap:
        name: aws-rds-ca
        defaultMode: 0444
    extraVolumeMounts:
    - name: aws-rds-ca
      mountPath: /home/appuser/.postgresql
    pdb:
      minAvailable: 33%
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: eth-keygen
