apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-turbo-api
  namespace: vaas-prod
spec:
  chart:
    spec:
      chart: podinfo
      interval: 5m
      version: '6.3.3'
      sourceRef:
        kind: HelmRepository
        name: kiln
        namespace: flux-system
  interval: 5m
  maxHistory: 2
