# Base configuration for Ethereum services.
#
# Values here can be overriden by corresponding environment
# variables (i.e: eth.htt-port -> ETH_HTTP_PORT).

eth:
  server:
    http-port: 8081
    http-debug-port: 8082
    is-recovery-mode: true

  api:
    slot0-ts: 1606824023
    # This is needed for Bitpanda /rewards on ~3K validators. Values
    # are aligned with the timeouts on core-api.
    postgresql:
      cl:
        timeout: 600s
      el:
        timeout: 600s
      dw:
        timeout: 600s
      stakes:
        timeout: 600s

  sla:
    buckets:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "10"
      - "15"
      - "30"
      - "60"
      - "180"
      - "360"
      - "600"

  dw.live:
    rpc:
      geth:
        host: ws://mainnet-geth-c-0.mainnet-geth-c.ethereum-common
        ws-port: 8546
    core-stake:
      endpoint: http://core-stake-api-core-stake-cli:8080
    official-deposit-contract-address: '0x00000000219ab540356cBB839Cbe05303d7705Fa'
    kiln-staking-contract-addresses:
      - 0x746d8A8FCAB7f829Fa500504f60D89C5CC1EA973
      - 0x1e68238cE926DEC62b3FBC99AB06eB1D85CE0270
      - 0x0816DF553a89c4bFF7eBfD778A9706a989Dd3Ce3
      - 0xEF650d5DbE75f39e2ec18A4381F75c8a4D4E19C8
    kiln-fee-recipient-contract-addresses:
      - 0xD1423C8DBd92Cf0b6087150818Cd9e3898f85287
      - 0x933fBfeb4Ed1F111D12A39c2aB48657e6fc875C6
      - 0xc7aB80841256AFD48a1e6e9b29F8Bc304A9Ed8f2
      - 0xAa9f0812d001A07eF9918354728d735a7919B717

  dw.finalizer:
    rpc:
      geth:
        host: http://mainnet-geth-c-0.mainnet-geth-c.ethereum-common
        http-port: 8545
    core-stake:
      endpoint: http://core-stake-api-core-stake-cli:8080
    official-deposit-contract-address: '0x00000000219ab540356cBB839Cbe05303d7705Fa'
    official-deposit-contract-deployment-block: 11052984
    kiln-staking-contract-addresses:
      - 0x746d8A8FCAB7f829Fa500504f60D89C5CC1EA973
      - 0x1e68238cE926DEC62b3FBC99AB06eB1D85CE0270
      - 0x0816DF553a89c4bFF7eBfD778A9706a989Dd3Ce3
      - 0xEF650d5DbE75f39e2ec18A4381F75c8a4D4E19C8
    kiln-fee-recipient-contract-addresses:
      - 0xD1423C8DBd92Cf0b6087150818Cd9e3898f85287
      - 0x933fBfeb4Ed1F111D12A39c2aB48657e6fc875C6
      - 0xc7aB80841256AFD48a1e6e9b29F8Bc304A9Ed8f2
      - 0xAa9f0812d001A07eF9918354728d735a7919B717
    kiln-organization-ids:
      - c2d7145e-b816-4620-ac8a-88ae4b621b04
      - 46458d3a-091e-4b9a-8c4c-5d92f3d2fc15
      - 7c80183d-262d-41b2-9626-a0da317c72d2
      - c62d6834-4b67-4c17-969c-8740bd9bfb46
    kiln-api-endpoint: https://api.kiln.fi
    min-blocks-required-for-finalization: 12
    iteration-interval: 5m

  dw.reconcile:
    core-stake:
      endpoint: http://core-stake-api-core-stake-cli:8080
    kiln-staking-contract-addresses:
      - 0x746d8A8FCAB7f829Fa500504f60D89C5CC1EA973
      - 0x1e68238cE926DEC62b3FBC99AB06eB1D85CE0270
      - 0x0816DF553a89c4bFF7eBfD778A9706a989Dd3Ce3
    kiln-fee-recipient-contract-addresses:
      - 0xD1423C8DBd92Cf0b6087150818Cd9e3898f85287
      - 0x933fBfeb4Ed1F111D12A39c2aB48657e6fc875C6
      - 0xc7aB80841256AFD48a1e6e9b29F8Bc304A9Ed8f2
    kiln-organization-ids:
      - c2d7145e-b816-4620-ac8a-88ae4b621b04
      - 46458d3a-091e-4b9a-8c4c-5d92f3d2fc15
      - 7c80183d-262d-41b2-9626-a0da317c72d2
    kiln-api-endpoint: https://api.kiln.fi

  ew:
    rpc:
      geth:
        host: http://mainnet-geth-c-0.mainnet-geth-c.ethereum-common
        http-port: 8545
    exit-contracts:
      kiln-addresses:
        - 0x004C226FFF73aA94b78a4Df1A0e861797BA16819
        - 0x746d8A8FCAB7f829Fa500504f60D89C5CC1EA973
        - 0x1e68238cE926DEC62b3FBC99AB06eB1D85CE0270
        - 0x0816DF553a89c4bFF7eBfD778A9706a989Dd3Ce3
        - 0xEF650d5DbE75f39e2ec18A4381F75c8a4D4E19C8
      kiln-trusted:
        - 0x746d8A8FCAB7f829Fa500504f60D89C5CC1EA973
        - 0x1e68238cE926DEC62b3FBC99AB06eB1D85CE0270
        - 0x0816DF553a89c4bFF7eBfD778A9706a989Dd3Ce3
        - 0xEF650d5DbE75f39e2ec18A4381F75c8a4D4E19C8
      lido-locator-address: 0xC1d0b3DE6792Bf6b4b37EccdcC24e45978Cfd2Eb
    earliest-block: 17031187
    lido-operator-idx: 8

  aggregator.netstats:
    network-queries:
      api-endpoint: https://api-beta.stakingrewards.com/v1/assets/overview/ethereum-2-0
    kiln-queries:
      api-endpoint: https://api.rated.network
      operator-id: Kiln
      network: mainnet
      sleep-between-queries: 1m
    refresh-rate: 1h

  aggregator.el:
    rpc:
      geth:
        host: mainnet-geth-c-0.mainnet-geth-c.ethereum-common
        http-port: 8545
      beacon:
        host: mainnet-lighthouse-beacon-archive-c-0.mainnet-lighthouse-beacon-archive-c.ethereum-common
        http-port: 5052
    merge-block: 15537394
    merge-slot: 4700013
    merge-ts: 1663224179
    block-start: 0

  aggregator.cl:
    rpc:
      beacon:
        host: mainnet-lighthouse-beacon-archive-c-0.mainnet-lighthouse-beacon-archive-c.ethereum-common
        http-port: 5052
    postgresql:
      cl:
        timeout: 45m

  keygen:
    deposit-cli: /usr/local/bin/deposit-cli
    keystore-converter: /usr/local/bin/eth2-keystore-converter
    vault-cli: /usr/bin/vault
    vault-token-path: /vault/secrets/token
    ethereum-chain: mainnet
    vault-ethereum-chain: mainnet
    vault-mnemonic-path: ethereum/mnemos

  sentinel:
    refresh-rate: 10m

  deployer:
    validator-clients:
      filepaths:
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/lighthouse/mainnet-lighthouse-validator-c-0.yaml
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/lighthouse/mainnet-lighthouse-validator-c-1.yaml
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/lighthouse/mainnet-lighthouse-validator-c-2.yaml
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/lighthouse/mainnet-lighthouse-validator-c-3.yaml
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/lighthouse/mainnet-lighthouse-validator-c-4.yaml
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/prysm/mainnet-prysm-validator-a-2.yaml
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/prysm/mainnet-prysm-validator-a-3.yaml
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/prysm/mainnet-prysm-validator-a-4.yaml
        - gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/teku/mainnet-teku-validator-b-2.yaml
      pubkeys-yaml-path: spec.values.config.validators-external-signer-public-keys
      el-fees-mapping-yaml-path: spec.values.recipients.proposer_config
    w3signer:
      filepath: gitops/apps/ethereum-web3signer/kiln-aws-mainnet-eu-west-1/mainnet-web3signer.yaml
      pubkeys-yaml-path: spec.values.vault.pubkeys
    environment: mainnet
    git-cli-debug: true

  exiter:
    exit-file:
      filepath: gitops/apps/ethereum-validators/kiln-aws-mainnet-eu-west-1/mainnet-exit-trigger.yaml
      pubkeys-yaml-path: spec.values.publicKeys
    environment: mainnet
    git-cli-debug: true
