# Base configuration for Ethereum services.
#
# Values here can be overriden by corresponding environment
# variables (i.e: eth.htt-port -> ETH_HTTP_PORT).

eth:
  server:
    http-port: 8081
    http-debug-port: 8082
    is-recovery-mode: true
