
pull_request_rules:
  - name: entry queue
    conditions:
      - label!=mainnet
      - label=renovate
    actions:
      queue:
        name: renovate

queue_rules:
  - name: renovate
    queue_conditions:
      - label=renovate
    merge_method: squash
    update_method: rebase
