apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: vaas-testnet
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: 6.3.5
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1

