apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-test
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/rguichard/flux-test
