apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role
rules:
  - apiGroups: []
    resources: ["pods"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-injector-agent-injector-leader-elector-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default

