apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ks2
spec:
  force: false
  interval: 10m0s
  path: ./ks2
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-test
