apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hr.yaml
configMapGenerator:
  - name: ada-base-config
    namespace: default
    behavior: replace
    files:
      - config=ada-base.config
configurations:
  - kustomizeconfig.yaml

