apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-exiter
  namespace: vaas-testnet
spec:
  chart:
    spec:
      chart: eth-cli
      interval: 5m
      version: '0.4.1'
      sourceRef:
        kind: HelmRepository
        name: kiln
        namespace: flux-system
  interval: 5m
  maxHistory: 2
  valuesFrom:
  - kind: ConfigMap
    name: eth-base-config
    targetPath: eth.config
    optional: false
  - kind: ConfigMap
    name: vaas-version
  values:
    replicaCount: 1
    serviceAccount:
      create: true
      name: eth-exiter
    eth:
      bin: './entrypoint.sh'
      command: exiter
    env:
      ETH_EXITER_POSTGRESQL_STAKES_DSN: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):$(POSTGRES_PORT)/eth_stakes?sslmode=verify-full"
    envFrom:
      POSTGRES_ENDPOINT:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-endpoint
      POSTGRES_PORT:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-port
      POSTGRES_USERNAME:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-username
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-password
      ETH_EXITER_GITHUB_TOKEN:
        valueFrom:
          secretKeyRef:
            name: github-token-rw
            key: token
    extraVolumes:
    - name: aws-rds-ca
      configMap:
        name: aws-rds-ca
        defaultMode: 0444
    extraVolumeMounts:
    - name: aws-rds-ca
      mountPath: /home/appuser/.postgresql
    nodeSelector:
      role: vaas
      network: private
    pdb:
      minAvailable: 0
