---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: eth-keygen
  namespace: vaas-testnet
spec:
  chart:
    spec:
      chart: eth-cli
      version: '0.4.1'
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: kiln
        namespace: flux-system
  interval: 5m
  maxHistory: 2
  valuesFrom:
    - kind: ConfigMap
      targetPath: eth.config
      name: eth-base-config
      optional: false
    - kind: ConfigMap
      name: vaas-version
  values:
    replicaCount: 2
    serviceAccount:
      create: true
      name: 'eth-keygen'
    eth:
      bin: './entrypoint.sh'
      command: 'keygen'
    vault:
      enabled: true
      address: 'https://vault.testnet.kiln.fi'
      role: 'vaas-eth-keygen'
      certificate:
        duration: 36h
        renewBefore: 30h
        issuerRef:
          kind: ClusterIssuer
          name: vault-clusterissuer
    env:
      ETH_KEYGEN_POSTGRESQL_DSN: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@$(POSTGRES_ENDPOINT):$(POSTGRES_PORT)/eth_stakes?sslmode=verify-full"
    enabledNetworkPolicy: true
    eksCIDR: "10.21.0.0/16"
    allowedEgressCIDRs:
      - "18.203.212.222/32" # NLB Vault eu-west-1
      - "63.34.24.253/32" # NLB Vault eu-west-1
      - "46.137.111.212/32" # NLB Vault eu-west-1
      - "52.47.198.41/32"  # NLB Vault eu-west-3
      - "13.36.80.218/32" # NLB Vault eu-west-3
      - "52.47.162.32/32" # NLB Vault eu-west-3
      - "10.21.96.0/19" # RDS subnet
      - "10.21.160.0/19" # RDS subnet
      - "10.21.128.0/19" # RDS subnet
    envFrom:
      POSTGRES_ENDPOINT:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-endpoint
      POSTGRES_PORT:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-port
      POSTGRES_USERNAME:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-username
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: vaas-postgresql
            key: postgresql-password
    agentRefresh:
      enabled: true
    nodeSelector:
      node.kubernetes.io/instance-type: t3a.xlarge
      network: private
      role: dedicated
    extraVolumes:
    - name: aws-rds-ca
      configMap:
        name: aws-rds-ca
        defaultMode: 0444
    extraVolumeMounts:
    - name: aws-rds-ca
      mountPath: /home/appuser/.postgresql
    pdb:
      minAvailable: 1
