# Base configuration for Ethereum services.
#
# Values here can be overriden by corresponding environment
# variables (i.e: eth.server.http-port maps to
# ETH_SERVER_HTTP_PORT).
eth:
  server:
    http-port: 8081
    http-debug-port: 8082
    is-recovery-mode: false

  api:
    slot0-ts: 1616508000

    # This is needed for Bitpanda /rewards on ~3K validators. Values
    # are aligned with the timeouts on core-api.
    postgresql:
      cl:
        timeout: 600s
      el:
        timeout: 600s
      dw:
        timeout: 600s
      stakes:
        timeout: 600s

  sla:
    buckets:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "10"
      - "15"
      - "30"
      - "60"
      - "180"
      - "360"
      - "600"

  dw.live:
    rpc:
      geth:
        host: ws://goerli-geth-a-0.goerli-geth-a.ethereum-common
        ws-port: 8546
    core-stake:
      endpoint: http://core-stake-api-core-stake-cli:8080
    official-deposit-contract-address: '0xff50ed3d0ec03ac01d4c79aad74928bff48a7b2b'
    kiln-staking-contract-addresses:
      - 0xe8Ff2a04837aac535199eEcB5ecE52b2735b3543
      - 0x3ab5aB25EbC61cEFCDCdc3CB301e47A3Bdb8E8b2
    kiln-fee-recipient-contract-addresses:
      - 0x1AcD717aDF8A3A1e4c23C6510cfbE76834E3f1bf
      - 0xA976EE883D7366E1A67C6A9fA9eFEEc9D6F2603E

  dw.finalizer:
    rpc:
      geth:
        host: http://goerli-geth-a-0.goerli-geth-a.ethereum-common
        http-port: 8545
    core-stake:
      endpoint: http://core-stake-api-core-stake-cli:8080
    official-deposit-contract-address: 0xff50ed3d0ec03ac01d4c79aad74928bff48a7b2b
    official-deposit-contract-deployment-block: 4367322
    kiln-staking-contract-addresses:
      - 0xe8Ff2a04837aac535199eEcB5ecE52b2735b3543
      - 0x3ab5aB25EbC61cEFCDCdc3CB301e47A3Bdb8E8b2
    kiln-fee-recipient-contract-addresses:
      - 0x1AcD717aDF8A3A1e4c23C6510cfbE76834E3f1bf
      - 0xA976EE883D7366E1A67C6A9fA9eFEEc9D6F2603E
    kiln-organization-ids:
      - 622da0f0-e4ff-4196-ae85-ba9f124df289
      - 3faf67cf-0e77-495c-a8d5-ff6daf922837
    kiln-api-endpoint: https://api.testnet.kiln.fi
    min-blocks-required-for-finalization: 12
    iteration-interval: 5m

  dw.reconcile:
    core-stake:
      endpoint: http://core-stake-api-core-stake-cli:8080
    kiln-staking-contract-addresses:
      - 0xe8Ff2a04837aac535199eEcB5ecE52b2735b3543
      - 0x3ab5aB25EbC61cEFCDCdc3CB301e47A3Bdb8E8b2
    kiln-fee-recipient-contract-addresses:
      - 0x1AcD717aDF8A3A1e4c23C6510cfbE76834E3f1bf
      - 0xA976EE883D7366E1A67C6A9fA9eFEEc9D6F2603E
    kiln-organization-ids:
      - 622da0f0-e4ff-4196-ae85-ba9f124df289
      - efcf478f-451d-4d06-a7a2-16fd12a30c34
      - 3faf67cf-0e77-495c-a8d5-ff6daf922837
    kiln-api-endpoint: https://api.testnet.kiln.fi

  ew:
    rpc:
      geth:
        host: http://goerli-geth-a-0.goerli-geth-a.ethereum-common
        http-port: 8545
    exit-contracts:
      kiln-addresses:
        - 0x0b846434cE660730c9D986C4febc12587c076CAD
        - 0xe8Ff2a04837aac535199eEcB5ecE52b2735b3543
        - 0x3ab5aB25EbC61cEFCDCdc3CB301e47A3Bdb8E8b2
        - 0x9c1D4220cA82115167A5da4c00c062C78Fd3D3F8
      kiln-trusted:
        - 0xe8Ff2a04837aac535199eEcB5ecE52b2735b3543
        - 0x3ab5aB25EbC61cEFCDCdc3CB301e47A3Bdb8E8b2
        - 0x9c1D4220cA82115167A5da4c00c062C78Fd3D3F8
      lido-locator-address: 0x1eDf09b5023DC86737b59dE68a8130De878984f5
    earliest-block: 8496071
    lido-operator-index: 6
    start-block: 9009438
#    operatord-report-url: http://operatord-exit.operatord:8080

  aggregator.netstats:
    network-queries:
      api-endpoint: https://api-beta.stakingrewards.com/v1/assets/overview/ethereum-2-0
    kiln-queries:
      api-endpoint: https://api.rated.network
      operator-id: Kiln
      network: prater
      sleep-between-queries: 1m
    refresh-rate: 1h

  aggregator.el:
    rpc:
      geth:
        host: goerli-geth-a-0.goerli-geth-a.ethereum-common
        http-port: 8545
      beacon:
        host: goerli-lighthouse-beacon-archive-c-0.goerli-lighthouse-beacon-archive-c.ethereum-common
        http-port: 5052
    merge-block: 7382819
    merge-slot: 3639527
    merge-ts: 1660182324
    block-start: 0

  aggregator.cl:
    slot0-ts: 1616508000
    rpc:
      beacon:
        host: goerli-lighthouse-beacon-archive-c-0.goerli-lighthouse-beacon-archive-c.ethereum-common
        http-port: 5052
    postgresql:
      cl:
        timeout: 1000s

  keygen:
    deposit-cli: /usr/local/bin/deposit-cli
    keystore-converter: /usr/local/bin/eth2-keystore-converter
    vault-cli: /usr/bin/vault
    vault-token-path: /vault/secrets/token
    ethereum-chain: prater
    vault-ethereum-chain: goerli
    vault-mnemonic-path: ethereum/mnemos

  sentinel:
    refresh-rate: 10m

  deployer:
    validator-clients:
      filepaths:
        - gitops/apps/ethereum-validators/kiln-aws-testnet-eu-west-1/prysm/goerli-prysm-validator-a-0.yaml
        - gitops/apps/ethereum-validators/kiln-aws-testnet-eu-west-1/teku/goerli-teku-validator-b-0.yaml
        - gitops/apps/ethereum-validators/kiln-aws-testnet-eu-west-1/lighthouse/goerli-lighthouse-validator-c-0.yaml
      pubkeys-yaml-path: spec.values.config.validators-external-signer-public-keys
      el-fees-mapping-yaml-path: spec.values.recipients.proposer_config
    w3signer:
      filepath: "gitops/apps/ethereum-web3signer/kiln-aws-testnet-eu-west-1/goerli-web3signer.yaml"
      pubkeys-yaml-path: spec.values.vault.pubkeys
    environment: testnet
    git-cli-debug: true

  exiter:
    exit-file:
      filepath: gitops/apps/ethereum-validators/kiln-aws-testnet-eu-west-1/goerli-exit-trigger.yaml
      pubkeys-yaml-path: spec.values.publicKeys
    environment: testnet
    git-cli-debug: true
