name: Enforce Approval for Rolebinding Changes

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  id-token: write
  contents: read

jobs:
  enforce_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Check for Kubernetes rolebindings
        id: check-rolebindings
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo ${{ github.event.issue.number }}
          ls -lR ${{ github.workspace }}
          for file in $(gh pr view ${{ github.event.issue.number }} --json files --jq '.files.[].path'); do
            if grep -Rl 'RoleBinding' $(realpath $file); then
              echo "Kubernetes rolebindings found in PR changes."
              echo "RBAC_CHANGED=true" >> $GITHUB_OUTPUT
            else
              echo "No Kubernetes rolebindings found in PR changes."
              echo "RBAC_CHANGED=false" >> $GITHUB_OUTPUT
            fi
          done
      - name: Request approval from specific user
        if: steps.check-rolebindings.outputs.rbac_changed == 'true'
        uses: hkusu/review-assign-action@v1
        with:
          reviewers: ArchiFleKs
          token: ${{ secrets.GITHUB_TOKEN }}
