name: OpenAPI Tests

on:
  repository_dispatch:
    # On deploys to devnet, testnet, and mainnet
    types:
      - HelmRelease/*.vaas-testnet

jobs:
  api_test_devnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Get chart version from testnet
        id: testnet
        run: |
          VERSION=$(echo ${{ github.event.client_payload.metadata.revision }} | cut -d '@' -f1)
          APP=$(echo ${{ github.event.client_payload.involvedObject.name }})
          grep -Rn $APP gitops/apps/vaas/kiln-aws-testnet-eu-west-1/
          yq -r "select(.metadata.name == \"$APP\") | .spec.chart.spec.chart" gitops/apps/vaas/kiln-aws-testnet-eu-west-1/*
          yq -r "select(.metadata.name == \"${APP}\") | .spec.chart.spec.chart" gitops/apps/vaas/kiln-aws-testnet-eu-west-1/*
          CHART=$(yq -r "select(.metadata.name == \"$APP\") | .spec.chart.spec.chart" gitops/apps/vaas/kiln-aws-testnet-eu-west-1/*)
          echo "chart=$CHART"
          echo VERSION=${VERSION} >> $GITHUB_OUTPUT
          echo APP=${APP} >> $GITHUB_OUTPUT
          echo CHART=${CHART} >> $GITHUB_OUTPUT

      # Patch the chart version in the mainnet Helm release manifest.
      - name: Set chart version in mainnet
        id: mainnet
        env:
          CHART_VERSION: ${{ steps.testnet.outputs.version }}
          CHART: ${{ steps.testnet.outputs.chart }}
          APP: ${{ steps.testnet.outputs.app }}
        run: |
          for file in $(find gitops/apps/vaas/kiln-aws-mainnet-eu-west-1/ -name "*.yaml" -exec yq -r "select(.spec.chart.spec.chart == \"$CHART\") | filename' {} \;) ; do
            echo "set chart version to ${CHART_VERSION} for HelmRelease ${APP}"
            yq eval '.spec.chart.spec.version=env(CHART_VERSION)' -i ./gitops/apps/vaas/kiln-aws-mainnet-eu-west-1/${file}
          done

      # Open a Pull Request if an upgraded is needed in mainnet.
      - name: Open promotion PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: promotion
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update ${{ steps.testnet.outputs.app }} to v${{ steps.testnet.outputs.version }}
          title: ${{ steps.testnet.outputs.app }} update ${{ steps.testnet.outputs.version }}
          body: |
            Promote demo release on mainnet to v${{ steps.testnet.outputs.version }}
