name: OpenAPI Tests

on:
  repository_dispatch:
    # On deploys to devnet, testnet, and mainnet
    types:
      - HelmRelease/*.vaas-testnet

jobs:
  api_test_devnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Get chart version from testnet
        id: testnet
        run: |
          VERSION=$(echo ${{ github.event.client_payload.metadata.revision }} | cut -d '@' -f1)
          echo "Client Payload: ${{ toJson(github.event.client_payload) }}"
          echo ${{ github.event.client_payload.involvedObject.name }}
