name: Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  actions: write
  pull-requests: write
  issues: write
  contents: read

jobs:
  job:
    runs-on: runner1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'echo'
        run: |
          echo "hello world"

